### ISSUE TITLE
How to use this sdk to do an application level remote attestation

### ISSUE THREAD

**Issue by huangyg11** [google/go-tpm#107]
For example, I write an application A, and run it in the shielded vm. How does the application prove to a remote third party that it is the correct application.

From https://google.github.io/tpm-js/#pg_attestation, I learned how to attest the system, but don't know how to add the application to the trust stack.

Thanks.

**Comment by awly** [comment]
Sorry for the slow response.
The basic idea would be to measure (hash) the application and record that in a PCR.
It would be a good idea to also measure anything up the call stack, up to the kernel.

Measurements are recorded in PCRs using Extend command.
PCR value for remote attestation is created via Quote.

The specifics depend on your setup and which TPM version you're using.

I know this is vague, but the solution is very environment-specific and there's no example you could just copy from. You could ask about the design elsewhere (maybe StackOverflow) and when you know the exact sequence of commands, raise an issue if they aren't available.

**Comment by huangyg11** [comment]
After some investigation, I have found a solution using linux IMA. The tpm just provide the bottom layer, and it need some OS hooks to measure applications. In terms of linux, it is IMA.
