### ISSUE TITLE
tpm2: Problem with expectedDigest in PolicyPCR

### ISSUE THREAD

**Issue by karandave-bc** [google/go-tpm#124]
When a key is sealed against some PCR values without providing **expectedDigest** in the **PolicyPCR** to get the policy to seal with, everything works fine. Below is the example of it. (I am creating a sessionHandle and Policy digest as mentioned in examples of go-tpm.)
**err := tpm2.PolicyPCR(rwc, sessHandle, nil /*expectedDigest*/, pcrSelection)**

But when expected/predicted value of PCR is provided in PolicyPCR to get the new policy to seal against expected PCR value, it gives me error. Below is the example of it. I am using **tpm2.AlgSHA256**.
**err := tpm2.PolicyPCR(rwc, sessHandle, expectedDigest, pcrSelection)**

Here **expectedDigest** is **[ ] byte** type and I am getting it as a value of command line flag/argument. (Also tried defining with direct value in the function).

Is there anything that I am missing here or doing incorrectly?

Below is a little code sample of what I am doing.

`
func seal (c *cli) {
          pcrs_slice := c.IntSlice("pcrs")
          expectedDigest := c.String("digest")
          
           pcrs := make([]int, len(pcrs_slice))
           copy(pcrs[:], pcrs_slice)
     
           digest := []byte(nil)
           if expectedDigest != noDigest {
                   digest, _ = hex.DecodeString(expectedDigest)
           }

           fmt.Printf("Digest: ")
           fmt.Println(hex.EncodeToString(digest[:]))          
          
          rwc, err := tpm2.OpenTPM(device)

          sessHandle, policy, err := policyPCRPasswordSession(rwc, pcrs, digest, objectPassword)
          if err != nil {
                fmt.Fprintf(os.Stderr, "unable to get policy: %v", err)
                os.Exit(1)
          }

          /*** code for seal and load ***/
}
`
`
func policyPCRPasswordSession(rwc io.ReadWriteCloser, pcrs []int, expectedDigest []byte, password string) (sessHandle tpmutil.Handle, policy []byte, retErr error) {
        // this is not a very secure session.
        sessHandle, _, err := tpm2.StartAuthSession(
                rwc,
                tpm2.HandleNull,  /*tpmKey*/
                tpm2.HandleNull,  /*bindKey*/
                make([]byte, 16), /*nonceCaller*/
                nil,              /*secret*/
                tpm2.SessionPolicy,
                tpm2.AlgNull,
                tpm2.AlgSHA256)
        if err != nil {
                return tpm2.HandleNull, nil, fmt.Errorf("unable to start session: %v", err)
        }

        pcrSelection := tpm2.PCRSelection{
                Hash: tpm2.AlgSHA256,
                PCRs: pcrs,
        }

        // An empty expected digest means that digest verification is skipped.
        if err := tpm2.PolicyPCR(rwc, sessHandle, expectedDigest, pcrSelection); err != nil {
                return sessHandle, nil, fmt.Errorf("unable to bind PCRs to auth policy: %v", err)
        }

        if err := tpm2.PolicyPassword(rwc, sessHandle); err != nil {
                return sessHandle, nil, fmt.Errorf("unable to require password for auth policy: %v", err)
        }

        policy, err = tpm2.PolicyGetDigest(rwc, sessHandle)
        if err != nil {
                return sessHandle, nil, fmt.Errorf("unable to get policy digest: %v", err)
        }
        return sessHandle, policy, nil
}
`

And these are the results for both the cases (with and without expectedDigest).
`
cat tmp.key | tpm2 seal -p 9 -hd 0x80000000 -d 46fd082b60a0ffa92cb32663dc3f6c67a04eb7902f7153f2274b6e5cc6d26e3c
Digest is : 46fd082b60a0ffa92cb32663dc3f6c67a04eb7902f7153f2274b6e5cc6d26e3c
Digest size is : 32
Digest value: [70 253 8 43 96 160 255 169 44 179 38 99 220 63 108 103 160 78 183 144 47 113 83 242 39 75 110 92 198 210 110 60]
unable to get policy: unable to bind PCRs to auth policy: parameter 1, error code 0x4 : value is out of range or is not correct for the context

cat tmp.key | tpm2 seal -p 9  -hd 0x80000000
Digest is :
Digest size is : 0
Digest value: []
Loaded sealed data with handle: 0x80000001
`

I also tried wrapping expectedDigest with tpmutil.U16Bytes here [https://github.com/google/go-tpm/blob/master/tpm2/tpm2.go#L728](url) .

Is there anything that I am missing here or doing incorrectly or do we need to change anything in tpm2 for this?

**Comment by karandave-bc** [comment]
I get following params/cmd while using expectedDigest directly here [https://github.com/google/go-tpm/blob/master/tpm2/tpm2.go#L741](url) 
                   **cmd, err := encodePolicyPCR(session, expectedDigest, sel)**
expectedDigest: [70 253 8 43 96 160 255 169 44 179 38 99 220 63 108 103 160 78 183 144 47 113 83 242 39 75 110 92 198 210 110 60]
params:  [3 0 0 0 0 32 70 253 8 43 96 160 255 169 44 179 38 99 220 63 108 103 160 78 183 144 47 113 83 242 39 75 110 92 198 210 110 60]
cmd:  [3 0 0 0 0 32 70 253 8 43 96 160 255 169 44 179 38 99 220 63 108 103 160 78 183 144 47 113 83 242 39 75 110 92 198 210 110 60 0 0 0 1 0 11 3 0 2 0]

unable to get policy: unable to bind PCRs to auth policy: parameter 1, error code 0x4 : value is out of range or is not correct for the context

And I get following params/cmd while using tpmutil.U16Bytes(expectedDigest).
                    **cmd, err := encodePolicyPCR(session, tpmutil.U16Bytes(expectedDigest), sel)**
expectedDigest: [70 253 8 43 96 160 255 169 44 179 38 99 220 63 108 103 160 78 183 144 47 113 83 242 39 75 110 92 198 210 110 60]
params:  [3 0 0 1 0 32 70 253 8 43 96 160 255 169 44 179 38 99 220 63 108 103 160 78 183 144 47 113 83 242 39 75 110 92 198 210 110 60]
cmd:  [3 0 0 1 0 32 70 253 8 43 96 160 255 169 44 179 38 99 220 63 108 103 160 78 183 144 47 113 83 242 39 75 110 92 198 210 110 60 0 0 0 1 0 11 3 0 2 0]

unable to get policy: unable to bind PCRs to auth policy: parameter 1, error code 0x4 : value is out of range or is not correct for the context

Do these look okay or expected? Both seem to have have proper digest value concated with params.

**Comment by awly** [comment]
https://github.com/google/go-tpm/pull/132 adds a test that you can use as an example.
Feel free to re-open this issue if it still doesn't work.
