### ISSUE TITLE
Release version v0.1.2 (or maybe bump to v0.2.X)?

### ISSUE THREAD

**Issue by twitchy-jsonp** [google/go-tpm#127]
Referencing go-tpm by hash from other modules is getting onerous. Is there appetite to release a new version?

**Comment by awly** [comment]
Good idea! Added a v0.2.0 tag from current master: https://github.com/google/go-tpm/releases/tag/v0.2.0
We should do this more often.

There's also potential to clean up some historic tech debt in tpm2, like merging CreatePrimary/CreatePrimaryEx and NVRead/NVReadEx.
We should tag v1 after that.

I also wanted to make TPM commands be methods on a type that holds the open fd.
That could also keep track of open handles and help clean them up.

Unfortunately I don't have much time to work on the library now, so contributions are welcome :)
