### ISSUE TITLE
Application for TPM1.2 Maintainership

### ISSUE THREAD

**Issue by ChriMarMe** [google/go-tpm#139]
Hello everyone,

Our company "9elements Cyber Security" https://9esec.io would like to apply for TPM1.2 maintainership.

Especially following team members @zaolin , @flanfly , @ChriMarMe 

Best Regards,
Christopher Meis

**Comment by ChriMarMe** [comment]
Hey everyone,

some feedback to the application would be nice.
We really want to step in here.

Best Regard
@ChriMarMe

**Comment by awly** [comment]
Thanks for volunteering!
cc @josephlr @twitchy-jsonp @stevenrutherford 

We've agreed to accept your application, with a temporary review shadowing setup:
- after you review and approve a PR, assign one of the current maintainers
- this maintainer will do a second pass on the PR
- after the second reviewer approves a PR, it can be merged

_This ensures we keep a consistent style and structure._

After some time (a few months), when second reviews result in few comments, we'll step back and let you review PRs without additional oversight.

I will put in a [CODEOWNERS](https://help.github.com/en/articles/about-code-owners) file so it's easier to find other maintainer usernames.

**Do you agree to this setup?**

**Comment by josephlr** [comment]
@ChriMarMe we generally use GitHub groups to mange who is admin/writer/etc... is there a specific group from your org that you would want to use here? If you don’t have one, that’s OK, we can just manually add a list of usernames.

**Comment by ChriMarMe** [comment]
@awly I agree to this setup

@josephlr We belong to the "Cyber Security" group of our organisation at github, but only the three people mentioned above will do the reviewing. So I suggest you just add us manually.

**Comment by awly** [comment]
@josephlr sounds like understand github permissions and `CODEOWNERS` well.
Do you mind setting up access for 9elements?

**Comment by josephlr** [comment]
Will do.

**Comment by zaolin** [comment]
Any updates so far?

**Comment by awly** [comment]
Ping @josephlr

**Comment by hugelgupf** [comment]
Hey @josephlr would you mind picking this up again? I'm happy to talk to you internally as well about this.

**Comment by ChriMarMe** [comment]
Hey, whats the status about this?

**Comment by josephlr** [comment]
Hey everyone, very sorry for the delay, this totally fell off my plate, I'm getting all of the groups setup now.

**Comment by hugelgupf** [comment]
Thank you!

**Comment by josephlr** [comment]
@ChriMarMe @zaolin @flanfly: I've sent you a invite to this repo giving you "Write" access. I don't know if you need "Maintain" access for anything you want to do. If it becomes an issue just let me know and I'll upgrade the access level for you all.

#161 adds you three as owners of the TPM1.2 code, adds the admins as global owners, and sets myself, @awly, and @twitchy-jsonp as default reviewers for the TPM 2.0 code and common code. People should comment there if that configuration doesn't work (or approve the request if it does).

**Comment by ChriMarMe** [comment]
Thank you! :+1:  :)
