### ISSUE TITLE
Should unpack of U16/U32Bytes validate a max size?

### ISSUE THREAD

**Issue by twitchy-jsonp** [google/go-tpm#154]
Malicious attacker-controlled input could make its way to `tpmutil.Unpack()` of `U32Bytes` or `U16Bytes`. For instance, calling `tpm.UnmarshalPubRSAPublicKey()` with `20ff ffff 2020 20ff ffff 2020` will cause a massive allocation, crashing the machine.

Given that `TPMUnmarshal` takes a reader, theres no upfront knowledge of the size of the buffer being processed.

Anyone have an opinion on these options?

1. Add a max size (maybe 1mb?) which is larger than all expected use-cases
2. Refactor `tpmutil.Unpack` to pass the size of the buffer down the chain so size prefix fields can be properly validated.

WDYT?

**Comment by awly** [comment]
Good idea.
The limit could be as small as 4k, to match https://github.com/google/go-tpm/blob/master/tpmutil/run.go#L28
But 1M seems like a safe limit.

**Comment by josephlr** [comment]
1M seems reasonable to me
