### ISSUE TITLE
Add APIs for TPM2_ECDH_ZGen and TPM2_ECDH_KeyGen commands

### ISSUE THREAD

**Issue by cshari-zededa** [google/go-tpm#156]
Refer to 14.4 and 14.5 of
https://www.trustedcomputinggroup.org/wp-content/uploads/TPM-Rev-2.0-Part-3-Commands-01.38.pdf

**Comment by twitchyliquid64** [comment]
I don't have cycles to implement this ATM, but based on the command [spec](https://trustedcomputinggroup.org/wp-content/uploads/TPM-Rev-2.0-Part-3-Commands-01.38.pdf) (page 96 as marked, or 110 in a PDF reader) it looks trivial. We already have a decoder for ECC point, so it should just be copy pasting an existing command and changing the parameters to match that of the new functions.

If you want to give implementing this a go, I'm happy to review.
