### ISSUE TITLE
TakeOwnership in go-tpm/tpm2

### ISSUE THREAD

**Issue by neeki-hushyar** [google/go-tpm#157]
Is there a go-tpm/tpm2 alternative to the TakeOwnership command from tpmv1.2?

It looks like the command code for TakeOwnership doesn't exist [here](https://trustedcomputinggroup.org/wp-content/uploads/TCG_TPM2_r1p55_Part2_Structures_pubrev.pdf#page=47) and
tpm2-tools lib uses a combination of tpm2_clear and tpm2_changeauth to achieve the same functionality.

However, I don't see the command codes for either of those in go-tpm/tpm2/constants.go - are there some other go-tpm functions I'm overlooking?

**Comment by twitchy-jsonp** [comment]
Hmmm, it does not look like `tpm2_clear` is implemented.

You don't necessarily need to call `tpm2_changeauth` if you are okay with the passwords being the empty buffer (20 bytes each with a value of zero).

**Comment by neeki-hushyar** [comment]
Thanks for merging PR. Closing issue
