### ISSUE TITLE
Question: Hiding or exporting structures

### ISSUE THREAD

**Issue by ChriMarMe** [google/go-tpm#173]
What is the policy for hiding or exporting structures?

In certain aspects im unsure if/when I'm allowed to export. Need some clarification here.
 
For example: tpm/GetPubKey returns a slice of bytes made from the pubkey structure. 
To use this information externally I have to make a struct again myself and parse it again.
So we parse data back and forth?! Or is this a question of clear abstraction between TDD and TSS?

For clarification:
The question came up, because we want to use go-tpm in a low memory environment, so building a huge framework around, like TCG TSS spec suggests, is way out of our scope. 

Thankful for input here :)

**Comment by ChriMarMe** [comment]
What just came to my mind: 
What if we seperate master (for normal OS like operation) and having a second branch for low memory environments (for example in u-root). In this branch we export more structures for external use. 

So we can cover both fields of application without interfering each other.

**Comment by twitchy-jsonp** [comment]
Basically we only export structures if they are needed. If they are command representations where we could get away with not exporting them, than that is preferable. Conversely, if the structure is the best way to communicate the data back to the user, than its okay to make it public.

Can you talk a little about the memory pressure you are experiencing? I would be incredibly surprised if having or not-having a few structures here and there makes any difference to runtime memory usage.

**Comment by ChriMarMe** [comment]
I'm not talking about runtime memory, but in u-root we somethimes have only 8 or 16 MB of Flash for Linuxboot. (and there we have Coreboot/TianoCore +Llinux kernel + uroot(initramfs))
Something like a tpm management engine is way too big in size and features for our application, but go-tpm (for tpm12, thats my main focus here) is insufficient in features to realize a standalone support for our purposes. 

For now, I will keep working on my urootdev branch and try to figure out later, what will make a good pr :D
