### ISSUE TITLE
Release tagged version 0.3.0

### ISSUE THREAD

**Issue by twitchy-jsonp** [google/go-tpm#180]
We haven't released a new version in a long while, we should do that.

**Comment by josephlr** [comment]
I agree with this, have we made breaking changes since the last release?

**Comment by twitchy-jsonp** [comment]
Its been ages, so probably?

**Comment by josephlr** [comment]
That's what I figured, we should make a list of any other functions we want to break back-compat on.

**Comment by josephlr** [comment]
This has been fixed, with the most recent release (that fixed the CVE).
