### ISSUE TITLE
TPM2 Seal command supporting NoDA attribute

### ISSUE THREAD

**Issue by chrisfenner** [google/go-tpm#187]
The [Seal](https://github.com/google/go-tpm/blob/89fb7a400ac7763655d11809afc01352dcacb22f/tpm2/tpm2.go#L562) function doesn't currently allow the caller to specify TPMA_OBJECT.NoDA to exempt the sealed blob from dictionary attacks. If the caller knows the auth value is not a low-entropy secret like a PIN or human-generated password, the caller should exempt their sealed data from dictionary attack prevention to improve reliability even if the TPM loses power (which counts as a dictionary attack attempt to the TPM)

A `SealEx` or similar command ought to be constructed, allowing the caller to pass the attributes to TPM2_Create.

**Comment by anatol** [comment]
Somewhat similar request. `tpm2_create` has `-a` parameter that allows to specify extra attributes. Some tools use it e.g. `tpm2_create -a "fixedtpm|fixedparent|noda|adminwithpolicy|userwithauth"`. I need to be able to specify attributes the same way from my golang code.

**Comment by chrisfenner** [comment]
I filed this almost a year ago intending to eventually get around to it myself 😅 feel free to send a PR and I'd be able to take a look. I still want to find time for this, but I can't promise I will soon.

**Comment by anatol** [comment]
https://github.com/google/go-tpm/pull/248 is the pull request for my changes.

Tested `SealEx()` with my code and it seems work fine.

**Comment by josephlr** [comment]
Closing as this can be done with `CreateKeyWithSensitive`, see https://github.com/google/go-tpm/pull/248#issuecomment-852537342
