### ISSUE TITLE
Storing keys (private, public) and compatibility with tpm2-tss / tpm2-tools

### ISSUE THREAD

**Issue by tobuh** [google/go-tpm#233]
I'm trying to stay compatible between tpm2-tss (resp. tpm2-tools) and my Golang implementation using go-tpm.

For example, I would like to create a key with go-tpm, and use it with tpm2-tools. I created a key with tpm2.CreateKey(), stored the resulting byte arrays in files, but using tpm2_load -u .. -r .. resulted in an error:

```
ERROR:esys:src/tss2-esys/api/Esys_Load.c:189:Esys_Load_Async() SAPI Prepare returned error. ErrorCode (0x0009000b) 
ERROR:esys:src/tss2-esys/api/Esys_Load.c:89:Esys_Load() Error in async function ErrorCode (0x0009000b) 
ERROR: Eys_Load(0x9000B) - mu:A parameter has a bad value
ERROR: Unable to run tpm2_load
```

As these files are two bytes smaller than those created with tpm2_create, I have the impression there are missing some prepending bytes in the blobs, giving the size or something. E.g. the public portion begins with:

```
0001 000b 0003 0432 0000 0006 0080 0043
0010 0800 0000 0000 0100 b7f7 2651 d736
```

Whereas another tpm2-tools generated public key begins with:

```
0116 0001 000b 0002 0032 0000 0010 0010
0800 0000 0000 0100 b093 8adc 6bae 05f9
```

What's the best practice for storing the key blobs, while staying compatible with tpm2-tools?

**Comment by twitchy-jsonp** [comment]
Internally our Go structures handle some of the serialization for you - such as a prepended length. That, or some other automatically computed field might account for the difference.

**Comment by twitchy-jsonp** [comment]
Yeah most of the return values of `CreateKey` are type `U16Bytes` - which means that they are serialized with a 2-byte length prefix:

https://github.com/google/go-tpm/blob/1ff48daca32f4907aebe8003f20ee45aede911a7/tpmutil/structures.go#L37-L54

If you are unpacking the byte slice manually, you'll need to reconstruct that prefix.

**Comment by tobuh** [comment]
Ahhhh, that's the function I was looking for! :man_facepalming:

**Comment by Kuenni** [comment]
Hi @tobuh,

I am trying to achieve the same thing like you and was referred to this issue. However, I am not able to use the key when I use the output of `key.TPMMarshal(os.Stdout)` because it still seems to be malformed. Could you share some information on how you were able to do that?

Thanks!

**Comment by tobuh** [comment]
@Kuenni 
Sorry for the late reply.

Maybe this will give you a hint (shortened code, may be not complete):

```
// Reading
publicFile, _:= os.OpenFile(filePathPublicBlob, ... )
publicBytes, _:= ioutil.ReadAll(publicFile)
tpmPublicBlob := tpmutil.U16Bytes(publicBytes)
buf := bytes.NewBuffer(tpmPublicBlob)
err := tpmPubBlob.TPMUnmarshal(buf)
// then use tpm functions

// Writing
private, public, _, _, _, _ := tpm2.CreateKey(...)
buf := &bytes.Buffer{}
tmpPublicKey := tpmutil.U16Bytes(public)
tmpPublicKey .TPMMarshal(buf)
file, _ := os.OpenFile(...)
io.Copy( file, bytes.NewReader(buf.Bytes()) )
// sync & close
```

**Comment by Kuenni** [comment]
@tobuh Thank You!
