### ISSUE TITLE
Supporting Apple Secure Enclave (T2 Chip)

### ISSUE THREAD

**Issue by Dentrax** [google/go-tpm#286]
I took a look at this project and couldn't find a related issue about supporting Apple T2 chip. (Since apple does not use TPM anymore in new CPUs) [^1] So I wanted to file an issue to discuss how can we bring a support for this.

Is it possible to make it work on macOS using Apple's [Secure Enclave](https://support.apple.com/en-gb/guide/security/sec59b0b31ff/web) T2 chip? If so, how? Do we need a low level interface to talk with the chip?

Related Works:
* [SecureEnclaveCrypto](https://github.com/trailofbits/SecureEnclaveCrypto)

Thanks!

[^1]: https://websuggestion.com/do-macs-have-tpm-answered-for-mac-users/

**Comment by josephlr** [comment]
This project (in general) is just for talking to devices, simulators, and other programs which use the TPM1.2 and TPM2 protocol. I don't think adding a third, proprietary protocol would be a good fit for this project. Ideally, there would be a separate library for talking the Mac Secure Enclave (if such a thing is even possible). Then, a higher-level libary or user application could provide an abstraction over these two protocols.

**Comment by josephlr** [comment]
I'm not aware if Apple allows third-party software to talk to the T2, it might just be limited to macOS itself.

Some links: https://github.com/duo-labs/apple-t2-xpc

**Comment by gedw99** [comment]
https://github.com/remko/age-plugin-se/tree/main/Sources 
- its swift talking to Apple Secure enclave

we can use cgo or no cgo approach. Both shown examle sin this Issue:

Issue raised here: https://github.com/Foxboron/swtpm_test/issues/1
