### ISSUE TITLE
reduce unnecessary overhead of Tbsi_Get_TCG_Log

### ISSUE THREAD

**Issue by rikuks** [google/go-tpm#325]
https://github.com/google/go-tpm/blob/3270509f088425fc9499bc9b7b8ff0811119bedb/tpmutil/tbs/tbs_windows.go#L261-L265

### Overview
The following image shows the result of reverse engineering tbs.dll.
<img width="579" alt="log" src="https://user-images.githubusercontent.com/120137336/230699664-2aa17dec-476c-4ee4-a2aa-06cb8f36d6a4.png">

The context that is the argument of `Tbsi_Get_TCG_Log` is unnecessary because it is never used in processing.

Thus it can be written as follows.
```go
 result, _, _ := tbsGetTCGLog.Call( 
 	0, 
 	sliceAddress(logBuffer), 
 	uintptr(unsafe.Pointer(&logBufferLen)), 
 ) 
```

### Conclusion

Contexts can be eliminated, thus reducing overhead.

**Comment by chrisfenner** [comment]
Hi, @rikuks, thanks for this pull request!

The official documentation for [Tbsi_Get_TCG_Log](https://learn.microsoft.com/en-us/windows/win32/api/tbs/nf-tbs-tbsi_get_tcg_log) promises to return `TBS_E_INVALID_CONTEXT` if passed an invalid context. I think we should avoid taking a dependency on something that might be broken without a change to the external API.
