### ISSUE TITLE
Support serialization of persistent handles

### ISSUE THREAD

**Issue by salrashid123** [google/go-tpm#342]
`tpm2_evictcontrol` supports serialization of the output value through its `-o` flag:

- [tpm2_evictcontrol](https://github.com/tpm2-software/tpm2-tools/blob/master/man/tpm2_evictcontrol.1.md#to-make-a-transient-handle-persistent-and-output-a-serialized-persistent-handle)
```
-o, --output=FILE:

Optionally output a serialized object representing the persistent handle. If untampered, these files are safer to use then raw persistent handles. A raw persistent handle should be verified that the object it points to is as expected.
```

which can be easily loaded and used for operatons even after reboot.

```bash
$ tpm2_createprimary -C o -c primary.ctx
$ tpm2_create -G rsa -u key.pub -r key.priv -C primary.ctx
$ tpm2_load -C primary.ctx -u key.pub -r key.priv -c key.ctx

$ echo "meet me at..." > secret.txt
$ tpm2_rsaencrypt -c key.ctx  -o secret.txt.enc secret.txt
$ tpm2_rsadecrypt -c key.ctx secret.txt.enc

$ tpm2_evictcontrol -C o -c key.ctx -o key.persisted
persistent-handle: 0x81000000
action: persisted

<reboot>

$ tpm2_rsadecrypt -c key.persisted secret.txt.enc

## ofcourse if the actual handle is evicted, key.persisted is useless
## $ tpm2_evictcontrol -C o -c  0x81000000
```

**Comment by chrisfenner** [comment]
Hi @salrashid123,

go-tpm aims to represent the TPM specification commands 1:1. The TPM doesn't have an opinion about how to remember your persisted handles, so neither does go-tpm. You could definitely use go-tpm to call EvictControl and save your handle value to a file, but it wouldn't be appropriate to expand go-tpm to do this work.
