### ISSUE TITLE
Consistancy between io.ReadWriter and io.ReadWriteCloser

### ISSUE THREAD

**Issue by josephlr** [google/go-tpm#60]
In go-tpm, the actual TPM device is passed as a generic go interface. For most of the functions in go-tpm this is a [`io.ReadWriter`](https://golang.org/pkg/io/#ReadWriter), however for [`GetRandom()`](https://github.com/google/go-tpm/blob/316d2c3af8a21149ef7630ccb8b8a75ecb0af6d2/tpm2/tpm2.go#L35) and [`ReadPCR()`](https://github.com/google/go-tpm/blob/316d2c3af8a21149ef7630ccb8b8a75ecb0af6d2/tpm2/tpm2.go#L154), the TPM is passed as a [`io.ReadWriteCloser`](https://golang.org/pkg/io/#ReadWriteCloser) despite the fact that neither of those methods call [`Close()`](https://golang.org/pkg/io/#Closer).

We should be consistent throughout go-tpm in use `io.ReadWriter` for our functions. Note that the signature of:
```go
func OpenTPM(path string) (io.ReadWriteCloser, error)
```
is fine as we need a way for a caller to close the TPM.

**Comment by shubhodeep9** [comment]
@josephlr is this issue open for working?

**Comment by awly** [comment]
It is technically a breaking change. Dependent code can rely on the func signature, for example when mocking out the command.

I'd like to get https://github.com/google/go-tpm/issues/58 done first, so we can break compatibility easily.

**Comment by awly** [comment]
@shubhodeep9 #58 is done so we can introduce breaking changes.
Feel free to send a PR if you're still interested.

**Comment by shubhodeep9** [comment]
@awly thanks for letting me know, I will start working on the PR.

**Comment by shubhodeep9** [comment]
@josephlr how does one test the changes?

**Comment by shubhodeep9** [comment]
@awly can we close this issue?

**Comment by awly** [comment]
Yep!
